# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "main" ]
  # pull_request:
  #   branches: [ "main" ]
  schedule:
    - cron: '0 12 * * *' # At 00:00 on Monday

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Run Script
      env: # Or as an environment variable
        MONGODB_URI: ${{ secrets.MONGODB_URI }}
        ZAPIER_WEBHOOK: ${{ secrets.ZAPIER_WEBHOOK }}
        TEST_SECRET: ${{ secrets.TEST_SECRET }}
        TEST_ENV_VARIABLE: ${{ secrets.sTEST_ENV_VARIABLE }}
      run: python main.py
